name: Deploy Typst Document

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: luiswirth/typst-deploy/.github/workflows/typst-deploy.yml@v4
    with:
      documents: |
        main.typ main.pdf
    secrets: inherit
